services:
  redis_gui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - '7843:7843'
    volumes:
      - /home/user/p3x-redis-ui-settings:/settings
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
  adminer:
    image: adminer
    restart: always
    ports:
      - '${ADMINER_PORT}:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - postgres-network
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: 'redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}'
    volumes:
      - redis-data:/data
networks:
  postgres-network:

volumes:
  postgres-data:
  redis-data:
